name: Test Cases Workflow

on: 
  push:
    branches: [assignment1]
jobs:
  test-cases:
    runs-on: ubuntu-latest
    steps:
      - name: change directory to server
        run: cd server 
      - name: run tests
        run: npm test